#!/usr/bin/env node
import { existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { frontmatter } from "./check-contract.mjs";

const groups = ["components", "layouts", "patterns"];
const urlPath = (path) => path.split(sep).map(encodeURIComponent).join("/");

function contractFiles(directory) {
  if (!existsSync(directory)) return [];
  if (lstatSync(directory).isSymbolicLink()) throw new Error(`symlink in contract directory: ${directory}`);
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = resolve(directory, entry.name);
    if (entry.isSymbolicLink()) throw new Error(`symlink in contract directory: ${path}`);
    return entry.isDirectory() ? contractFiles(path) : entry.isFile() && entry.name.endsWith(".md") ? [path] : [];
  });
}

function descriptionAtIndex(description, file, directory) {
  // Inline Markdown links keep their targets when copied one directory up.
  return description.replace(/(\[[^\]]*\]\(\s*)(?:<([^>]+)>|([^\s)]+))/g, (match, prefix, bracketed, plain) => {
    const target = bracketed ?? plain;
    if (/^(?:[a-z][a-z0-9+.-]*:|\/\/|\/)/i.test(target)) return match;
    const hash = target.indexOf("#");
    const path = hash < 0 ? target : target.slice(0, hash);
    const fragment = hash < 0 ? "" : target.slice(hash);
    const destination = path ? resolve(dirname(file), decodeURIComponent(path)) : file;
    return prefix + urlPath(relative(directory, destination)) + fragment;
  });
}

export function generateIndexes(project, { check = false } = {}) {
  const root = realpathSync(project);
  if (!existsSync(resolve(root, "DESIGN.md"))) throw new Error("missing DESIGN.md at project root");
  const directory = resolve(root, "design-system");
  if (existsSync(directory) && lstatSync(directory).isSymbolicLink()) throw new Error(`symlinked design-system directory: ${directory}`);
  const ids = new Set();
  // Prepare every index before writing: invalid metadata must not publish a partial set.
  const outputs = groups.map((group) => {
    const contracts = contractFiles(resolve(directory, group)).map((file) => {
      if (!realpathSync(file).startsWith(root + sep)) throw new Error(`contract resolves outside project: ${file}`);
      const { metadata, body, problems } = frontmatter(readFileSync(file, "utf8"));
      if (problems.length) throw new Error(`${file}: ${problems.join("; ")}`);
      if (ids.has(metadata.id)) throw new Error(`duplicate contract id: ${metadata.id}`);
      ids.add(metadata.id);
      const title = body.trimStart().match(/^# ([^\n]+)(?:\n|$)/)?.[1].trim();
      if (!title) throw new Error(`${file}: missing H1 name`);
      return { ...metadata, title, file };
    }).filter(({ status }) => status === "discoverable")
      .sort((a, b) => a.id < b.id ? -1 : a.id > b.id ? 1 : 0);
    const entries = contracts.map(({ title, file, description }) =>
      `- **${title}**\n  - Description: ${descriptionAtIndex(description, file, directory).replace(/\n(?=.)/g, "\n    ")}\n  - Contract: [contract](${urlPath(relative(directory, file))})\n`);
    const path = resolve(directory, `${group.toUpperCase()}.md`);
    if (lstatSync(path, { throwIfNoEntry: false })?.isSymbolicLink()) throw new Error(`symlinked index: ${path}`);
    const text = `# ${group[0].toUpperCase() + group.slice(1)}\n\n<!-- Generated by generate-indexes.mjs; edit contracts, then regenerate. -->\n\n${entries.join("\n")}`.trimEnd() + "\n";
    return { path, text };
  });
  const stale = outputs.filter(({ path, text }) => !existsSync(path) || readFileSync(path, "utf8") !== text);
  if (!check) {
    mkdirSync(directory, { recursive: true });
    for (const { path, text } of stale) writeFileSync(path, text);
  }
  return stale.map(({ path }) => path);
}

if (process.argv[1] && realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url))) {
  const args = process.argv.slice(2);
  const paths = args.filter((arg) => !arg.startsWith("--"));
  if (paths.length !== 1 || args.some((arg) => arg.startsWith("--") && arg !== "--check")) {
    console.error("usage: generate-indexes [--check] <project-root>");
    process.exit(2);
  }
  try {
    const check = args.includes("--check");
    const stale = generateIndexes(paths[0], { check });
    for (const path of stale) console.log(`${check ? "stale" : "updated"} ${path}`);
    process.exitCode = check && stale.length ? 1 : 0;
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
